# compose 파일 버전
version: '3'
services: 
  # 서비스 명
  postgres:
    # 사용할 이미지
    image: pgimage
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: pgimageContainer
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5432:5432"
    # 환경 변수 설정
    environment: 
      # PostgreSQL 계정 및 패스워드 설정 옵션
      # POSTGRES_USER: ${POSTGRES_UESR}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mirero
    # 환경 변수 저장 파일
    # env_file:
    #   - postsqlInfo.envpgadmin4
    # 볼륨 설정
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
      

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
    depends_on:
      - postgres