version: "3.8"

services:
  redis: # container name
    image: redis:6.2.6-alpine
    ports: # 바인딩할 포트:내부 포트
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    volumes: # 마운트할 볼륨 설정
      - ${REDIS_DATA_PATH}:/data
    restart: always